### ISSUE TITLE
add publiccode.yml

### ISSUE THREAD

**Issue by Smart-City-Muenster** [reedu-reengineering-education/smart-city-dashboard#11]
To make this project automatically more visible, we need a `publiccode.yml` file.
Here are [the docs about publiccode.yml](https://publiccodeyml.readthedocs.io/en/latest/) (and [the repo](https://github.com/publiccodeyml/publiccode.yml)) and here is [an online tool to generate this file](https://publiccode-editor.developers.italia.it/).

@felixerdy Let me know, if you are able to create a first version of this file or if I should create a pull request.

**Comment by Smart-City-Muenster** [comment]
See #12

**Comment by felixerdy** [comment]
closed in #13
