### ISSUE TITLE
Feature Request: Beim Aasee fehlt ein Button für die Monats übersicht

### ISSUE THREAD

**Issue by supertobi** [reedu-reengineering-education/smart-city-dashboard#7]
Beim Aasee fehlt ein Button für die Monats Übersicht, so wie es ihn bei den Passant:innen gibt

**Comment by Smart-City-Muenster** [comment]
Der Monatsbutton "fehlt" auch bei dden Wetter- und den Parkhausdaten. Das hat hauptsächlich UI-Gründe. @felixerdy wie aufwändig wäre es, Monatsbuttons auch für die anderen Widgets zu ergänzen?
