### ISSUE TITLE
Bug: Parkplätze am Schlossplatz sind immer voll

### ISSUE THREAD

**Issue by supertobi** [reedu-reengineering-education/smart-city-dashboard#8]
Die Parkplätze am Schlossplatz sind immer voll, da scheint etwas mit euren Daten nicht zu stimmen.

**Comment by Smart-City-Muenster** [comment]
Tatsächlich werden die Schlossplatz-Parkplätze teilweise als komplett belegt angezeigt, obwohl "geschlossen" korrekter wäre. Zu bestimmten Zeiten ist der Parkplatz nämlich nicht für Autos benutzbar. Zum Beispiel war Send als Du das Issue erstellt hast. In den Daten steht dann, dass alle Plätze belegt sind. Folgender aktueller Screenshot zeigt, dass die Daten ansonsten korrekt funktionieren.

![grafik](https://user-images.githubusercontent.com/84011331/150356980-c116d5fc-8a8c-447b-9d4a-bd5ffd6a7f9d.png)

**Comment by supertobi** [comment]
Send ja, da ist geschlossen, klar. 
Aber wenn man sich die schwarze Linie vom "PP Schlossplatz Süd" anschaut, das ist kein Verlauf den ich erwarten würde. kann natürlich trotzdem richtig sein.
Morgens leer, dann füllt er sich langsam. Mittags fahren dann spontan ~100 Autos vom Platz, dann füllt es sich wider.
Im Vergleich dazu  "PP Theater" so etwas würde ich erwarten.  
![grafik](https://user-images.githubusercontent.com/653976/150802509-5ddb1941-ad00-4ab3-a7f7-082da660e8a5.png)

**Comment by Smart-City-Muenster** [comment]
Danke fürs aufmerksame Beobachten. Ich konnte die Frage nach der Datenqualität mit dem zuständigen Fachamt klären: 

> die Sprünge im PLS am Schlossplatz kommen dadurch zustande, dass die Mitarbeiter von Westfalenfleiss, die diesen Parkplatz betreuen, aktuell noch mittags beim Schichtwechsel eine manuelle Nachkorrektur vornehmen müssen.
>
> Durch die Bauarbeiten für die Anti Terror Poller waren Oberflächen an den Ein- und Ausfahrten zerstört worden, in denen Induktionsschleifen für die automatische Zählung lagen. Diese Induktionsschleifen konnten bisher noch nicht wieder hergestellt werden, weil die Oberflächen bisher noch nicht endgültig, sondern nur provisorisch wieder hergestellt worden sind. Wir sind da aber am Ball ...

Die Daten werden also, sobald die Oberflächen endgültig wieder hergestellt sind, wieder vollständig korrekt angezeigt.
