### ISSUE TITLE
Anzahl Fahrradzählstellen

### ISSUE THREAD

**Issue by christophfriedrich** [reedu-reengineering-education/smart-city-dashboard#9]
Im Infotext im Dashboard steht es gäbe in Münster neun Stück. Auf der verlinkten Seite der Stadt wird von zehn gesprochen. So oder so fragt man sich, warum dann im Dashboard nur sechs enthalten sind.

**Comment by Smart-City-Muenster** [comment]
Danke für den Hinweis. Im Infotext ist von der Zählstation am Neutor die Rede und von neun weiteren, das sind also zehn Stationen insgesamt. Auf der Startseite des Dashboards werden aus Platzgründen nur 6 Zählstellen angezeigt, die restlichen 4* Stationen sind über die Kartenansicht einsehbar.

*Tatsächlich haben wir aber auf der Kartenansicht des Dashboards die Zählstation auf der Wolbecker Straße vergessen. @felixerdy Wie aufwändig wäre es, die noch hinzuzufügen?

**Comment by felixerdy** [comment]
Ich glaube das ist nicht so aufwändig. Ich schau es mir mal an
